INSERT INTO Categories VALUES (0, 'Baby Care');
INSERT INTO Categories VALUES (661, 'Beverages');
INSERT INTO Categories VALUES (2, 'Bread & Bakery');
INSERT INTO Categories VALUES (3, 'Breakfast & Cereal');
INSERT INTO Categories VALUES (4, 'Canned Goods & Soups');
INSERT INTO Categories VALUES (5, 'Condiments, Spice & Bake');
INSERT INTO Categories VALUES (6, 'Cookies, Snacks & Candy');
INSERT INTO Categories VALUES (7, 'Dairy, Eggs & Cheese');
INSERT INTO Categories VALUES (8, 'Deli');
INSERT INTO Categories VALUES (102, 'Flowers');
INSERT INTO Categories VALUES (10, 'Frozen Foods');
INSERT INTO Categories VALUES (11, 'Fruits & Vegetables');
INSERT INTO Categories VALUES (12, 'Grains, Pasta & Sides');
INSERT INTO Categories VALUES (13, 'International Cuisine');
INSERT INTO Categories VALUES (14, 'Meat & Seafood');
INSERT INTO Categories VALUES (15, 'Paper, Cleaning & Home');
INSERT INTO Categories VALUES (16, 'Personal Care & Health');
INSERT INTO Categories VALUES (17, 'Pet Care');
INSERT INTO Categories VALUES (18, 'Wine, Beer & Spirits');
INSERT INTO Categories VALUES (19, 'Formula & Baby Food');
INSERT INTO Categories VALUES (20, 'Diapers & Wipes');
INSERT INTO Categories VALUES (21, 'Baby Bath & Skin Care');
INSERT INTO Categories VALUES (22, 'Baby Accessories');
INSERT INTO Categories VALUES (23, 'Juice & Smoothies');
INSERT INTO Categories VALUES (24, 'Coffee');
INSERT INTO Categories VALUES (25, 'Soft Drinks');
INSERT INTO Categories VALUES (26, 'Tea');
INSERT INTO Categories VALUES (27, 'Water & Sparkling Water');
INSERT INTO Categories VALUES (244, 'Energy Drinks & Shots');
INSERT INTO Categories VALUES (245, 'Sports Drinks');
INSERT INTO Categories VALUES (246, 'Kombucha');
INSERT INTO Categories VALUES (247, 'Coconut Water');
INSERT INTO Categories VALUES (248, 'Cocoa & Hot Chocolate');
INSERT INTO Categories VALUES (33, 'Cakes & Cupcakes');
INSERT INTO Categories VALUES (34, 'Cookies & Bakery Snacks');
INSERT INTO Categories VALUES (35, 'Desserts & Cheesecakes');
INSERT INTO Categories VALUES (258, 'Baguettes & French Bread');
INSERT INTO Categories VALUES (37, 'Breakfast & Donuts');
INSERT INTO Categories VALUES (38, 'Buns & Rolls');
INSERT INTO Categories VALUES (39, 'Sandwich Breads');
INSERT INTO Categories VALUES (40, 'Bagels & Muffins');
INSERT INTO Categories VALUES (41, 'Pitas & Flatbreads');
INSERT INTO Categories VALUES (273, 'Bakery Catering Trays');
INSERT INTO Categories VALUES (274, 'Cereal');
INSERT INTO Categories VALUES (44, 'Frozen Breakfast');
INSERT INTO Categories VALUES (45, 'Breakfast Bars & Bites');
INSERT INTO Categories VALUES (290, 'Pancake & Waffle Mix');
INSERT INTO Categories VALUES (47, 'Syrup');
INSERT INTO Categories VALUES (292, 'Toaster Pastries');
INSERT INTO Categories VALUES (293, 'Instant Breakfast Drink');
INSERT INTO Categories VALUES (50, 'Soups & Ramen');
INSERT INTO Categories VALUES (51, 'Canned Vegetables');
INSERT INTO Categories VALUES (52, 'Canned Seafood & Fish');
INSERT INTO Categories VALUES (53, 'Canned Beans');
INSERT INTO Categories VALUES (54, 'Canned Tomatoes');
INSERT INTO Categories VALUES (55, 'Canned Fruit');
INSERT INTO Categories VALUES (56, 'Stocks, Broth & Bouillon');
INSERT INTO Categories VALUES (57, 'Canned Meals');
INSERT INTO Categories VALUES (58, 'Canned Meat');
INSERT INTO Categories VALUES (59, 'Seasoning,Spices & Herbs');
INSERT INTO Categories VALUES (60, 'Sauce, Marinades & Mixes');
INSERT INTO Categories VALUES (61, 'Salad Dressing & Topping');
INSERT INTO Categories VALUES (62, 'Jam,Spreads & Condiments');
INSERT INTO Categories VALUES (63, 'Baking Ingredients');
INSERT INTO Categories VALUES (64, 'Baking Dough & Mixes');
INSERT INTO Categories VALUES (65, 'Baking Supplies & Decor');
INSERT INTO Categories VALUES (66, 'Vinegar & Oil');
INSERT INTO Categories VALUES (67, 'Pickles, Relish & Olives');
INSERT INTO Categories VALUES (68, 'Honey, Syrup & Nectar');
INSERT INTO Categories VALUES (69, 'Chips');
INSERT INTO Categories VALUES (450, 'Cookies');
INSERT INTO Categories VALUES (456, 'Chocolate');
INSERT INTO Categories VALUES (72, 'Crackers');
INSERT INTO Categories VALUES (465, 'Candy');
INSERT INTO Categories VALUES (74, 'Candy - Seasonal');
INSERT INTO Categories VALUES (75, 'Salsa & Dips');
INSERT INTO Categories VALUES (76, 'Popcorn & Grain Cakes');
INSERT INTO Categories VALUES (77, 'Nuts, Seeds & Trail Mix');
INSERT INTO Categories VALUES (477, 'Gum');
INSERT INTO Categories VALUES (79, 'Fruit Cups & Applesauce');
INSERT INTO Categories VALUES (80, 'Jerky & Meat Snacks');
INSERT INTO Categories VALUES (481, 'Fruit Snacks');
INSERT INTO Categories VALUES (482, 'Pretzels');
INSERT INTO Categories VALUES (483, 'Mints');
INSERT INTO Categories VALUES (489, 'Gelatin & Pudding');
INSERT INTO Categories VALUES (85, 'Yogurt & Pudding');
INSERT INTO Categories VALUES (86, 'Cheese');
INSERT INTO Categories VALUES (87, 'Milk & Cream');
INSERT INTO Categories VALUES (88, 'Butter & Sour Cream');
INSERT INTO Categories VALUES (512, 'Eggs');
INSERT INTO Categories VALUES (90, 'Deli Cheese');
INSERT INTO Categories VALUES (91, 'Deli Meat');
INSERT INTO Categories VALUES (92, 'Deli Sides & Meals');
INSERT INTO Categories VALUES (521, 'Deli Salads');
INSERT INTO Categories VALUES (94, 'Deli Specialty Foods');
INSERT INTO Categories VALUES (95, 'Deli Dips & Hummus');
INSERT INTO Categories VALUES (530, 'Deli Catering Trays');
INSERT INTO Categories VALUES (531, 'Deli Soups');
INSERT INTO Categories VALUES (98, 'Deli Snacks Packs');
INSERT INTO Categories VALUES (99, 'Deli Sandwiches & Wraps');
INSERT INTO Categories VALUES (533, 'Deli Pizza');
INSERT INTO Categories VALUES (101, 'Sushi');
INSERT INTO Categories VALUES (534, 'Decor');
INSERT INTO Categories VALUES (104, 'Frozen Meals & Sides');
INSERT INTO Categories VALUES (105, 'Ice Cream & Novelties');
INSERT INTO Categories VALUES (549, 'Frozen Vegetables');
INSERT INTO Categories VALUES (107, 'Frozen Appetizers');
INSERT INTO Categories VALUES (108, 'Frozen Fruits & Dessert');
INSERT INTO Categories VALUES (109, 'Ice & Frozen Juice');
INSERT INTO Categories VALUES (110, 'Packaged Produce');
INSERT INTO Categories VALUES (111, 'Fresh Vegetables & Herbs');
INSERT INTO Categories VALUES (112, 'Nuts & Dried Fruits');
INSERT INTO Categories VALUES (113, 'Fresh Fruits');
INSERT INTO Categories VALUES (114, 'Pasta Sauce');
INSERT INTO Categories VALUES (360, 'Pasta');
INSERT INTO Categories VALUES (116, 'Rice Side Dishes');
INSERT INTO Categories VALUES (117, 'Macaroni & Cheese');
INSERT INTO Categories VALUES (118, 'Rice');
INSERT INTO Categories VALUES (119, 'Potato Side Dishes');
INSERT INTO Categories VALUES (120, 'Skillet Dinners & Sides');
INSERT INTO Categories VALUES (121, 'Dry Beans & Lentils');
INSERT INTO Categories VALUES (122, 'Pasta Side Dishes');
INSERT INTO Categories VALUES (123, 'Pizza Crust & Sauce');
INSERT INTO Categories VALUES (654, 'Stuffing Mix');
INSERT INTO Categories VALUES (125, 'Grains');
INSERT INTO Categories VALUES (126, 'Hispanic Foods');
INSERT INTO Categories VALUES (127, 'Asian Foods');
INSERT INTO Categories VALUES (668, 'Kosher Foods');
INSERT INTO Categories VALUES (129, 'More International Foods');
INSERT INTO Categories VALUES (691, 'Beef');
INSERT INTO Categories VALUES (131, 'Sausage,Hot Dogs & Bacon');
INSERT INTO Categories VALUES (132, 'Salami & Lunch Meats');
INSERT INTO Categories VALUES (133, 'Prepared & Frozen Meat');
INSERT INTO Categories VALUES (134, 'Fish & Shellfish');
INSERT INTO Categories VALUES (689, 'Chicken & Turkey');
INSERT INTO Categories VALUES (692, 'Pork');
INSERT INTO Categories VALUES (708, 'Lamb');
INSERT INTO Categories VALUES (138, 'Paper Products');
INSERT INTO Categories VALUES (139, 'Hardware & Home Needs');
INSERT INTO Categories VALUES (140, 'Kitchen Accessories');
INSERT INTO Categories VALUES (141, 'Cleaners & Supplies');
INSERT INTO Categories VALUES (142, 'Air Fresheners & Candles');
INSERT INTO Categories VALUES (143, 'Laundry');
INSERT INTO Categories VALUES (144, 'Plastic, Foil & Storage');
INSERT INTO Categories VALUES (145, 'Tableware & Trash Bags');
INSERT INTO Categories VALUES (146, 'Dish Detergents');
INSERT INTO Categories VALUES (147, 'Fire Logs & BBQ Needs');
INSERT INTO Categories VALUES (148, 'Skin Care & Cosmetics');
INSERT INTO Categories VALUES (149, 'Hair Care');
INSERT INTO Categories VALUES (150, 'Vitamins & Supplements');
INSERT INTO Categories VALUES (151, 'Oral Hygiene');
INSERT INTO Categories VALUES (152, 'Cold & Allergy');
INSERT INTO Categories VALUES (153, 'Nutrition Solutions');
INSERT INTO Categories VALUES (154, 'Antacid & Digestive Aids');
INSERT INTO Categories VALUES (833, 'Pain Relief');
INSERT INTO Categories VALUES (156, 'First Aid & Medical Care');
INSERT INTO Categories VALUES (157, 'Feminine Care');
INSERT INTO Categories VALUES (158, 'Deodorants');
INSERT INTO Categories VALUES (159, 'Eye & Ear Care');
INSERT INTO Categories VALUES (160, 'Shave Needs');
INSERT INTO Categories VALUES (161, 'Foot Care');
INSERT INTO Categories VALUES (864, 'Trial Size');
INSERT INTO Categories VALUES (163, 'Personal & Adult Care');
INSERT INTO Categories VALUES (164, 'Family Planning');
INSERT INTO Categories VALUES (165, 'Pantyhose & Apparel');
INSERT INTO Categories VALUES (166, 'Dog Care');
INSERT INTO Categories VALUES (167, 'Cat Care');
INSERT INTO Categories VALUES (168, 'Small Animal Care');
INSERT INTO Categories VALUES (169, 'Wine');
INSERT INTO Categories VALUES (170, 'Spirits & Mixers');
INSERT INTO Categories VALUES (171, 'Beer');
INSERT INTO Categories VALUES (172, '2nd Foods');
INSERT INTO Categories VALUES (173, 'Baby Formula');
INSERT INTO Categories VALUES (174, 'Toddler Bakery & Snacks');
INSERT INTO Categories VALUES (175, '1st Foods');
INSERT INTO Categories VALUES (176, 'Toddler Foods');
INSERT INTO Categories VALUES (177, 'Electrolyte Solution');
INSERT INTO Categories VALUES (178, 'Baby Cereal');
INSERT INTO Categories VALUES (179, '3rd Foods');
INSERT INTO Categories VALUES (180, 'Baby Juice & Beverages');
INSERT INTO Categories VALUES (181, 'Nutritional Supplements');
INSERT INTO Categories VALUES (182, 'Wipes & Diaper Refills');
INSERT INTO Categories VALUES (183, 'Training Pants');
INSERT INTO Categories VALUES (184, 'Diapers - Size 4');
INSERT INTO Categories VALUES (185, 'Diapers - Size 5');
INSERT INTO Categories VALUES (186, 'Diapers - Size 3');
INSERT INTO Categories VALUES (187, 'Diapers - Size 6 & Above');
INSERT INTO Categories VALUES (188, 'Diapers - Size 2');
INSERT INTO Categories VALUES (189, 'Diapers - Size 1');
INSERT INTO Categories VALUES (190, 'Diapers - Newborn');
INSERT INTO Categories VALUES (191, 'Baby Lotion & Oil');
INSERT INTO Categories VALUES (192, 'Baby Body Wash');
INSERT INTO Categories VALUES (193, 'Diaper Cream & Ointments');
INSERT INTO Categories VALUES (194, 'Baby Shampoo');
INSERT INTO Categories VALUES (195, 'Baby Powder');
INSERT INTO Categories VALUES (196, 'Pacifiers & Teethers');
INSERT INTO Categories VALUES (197, 'Bottles & Nursing');
INSERT INTO Categories VALUES (198, 'Cups & Placeware');
INSERT INTO Categories VALUES (199, 'Toys & Accessories');
INSERT INTO Categories VALUES (200, 'Health & Safety');
INSERT INTO Categories VALUES (201, 'Smoothies');
INSERT INTO Categories VALUES (202, 'Fruit Drink Mix');
INSERT INTO Categories VALUES (203, 'Orange Juice');
INSERT INTO Categories VALUES (204, 'Cranberry Juice');
INSERT INTO Categories VALUES (205, 'Berry & Blends');
INSERT INTO Categories VALUES (206, 'Juice Packs');
INSERT INTO Categories VALUES (207, 'Apple Juice & Cider');
INSERT INTO Categories VALUES (208, 'Lemonade & Limeade');
INSERT INTO Categories VALUES (209, 'Vegetable & Tomato Juice');
INSERT INTO Categories VALUES (210, 'Fruit Punch');
INSERT INTO Categories VALUES (211, 'Lemon & Lime Juice');
INSERT INTO Categories VALUES (212, 'Nectars');
INSERT INTO Categories VALUES (213, 'Grape Juice');
INSERT INTO Categories VALUES (214, 'Sparkling Juice');
INSERT INTO Categories VALUES (215, 'Pineapple Juice');
INSERT INTO Categories VALUES (216, 'Pomegranate Juice');
INSERT INTO Categories VALUES (217, 'Grapefruit Juice');
INSERT INTO Categories VALUES (218, 'Prune Juice');
INSERT INTO Categories VALUES (219, 'Coffee - Ground');
INSERT INTO Categories VALUES (220, 'Coffee - Pods');
INSERT INTO Categories VALUES (221, 'Iced & Nitro Coffee');
INSERT INTO Categories VALUES (222, 'Coffee - Whole Bean');
INSERT INTO Categories VALUES (223, 'Instant Coffee & Mix');
INSERT INTO Categories VALUES (224, 'Coffee Creamers');
INSERT INTO Categories VALUES (225, 'Flavored Syrups');
INSERT INTO Categories VALUES (226, 'Coffee Filters');
INSERT INTO Categories VALUES (227, 'Cola');
INSERT INTO Categories VALUES (228, 'Specialty & Natural Soda');
INSERT INTO Categories VALUES (229, 'Lemon Lime & Citrus Soda');
INSERT INTO Categories VALUES (230, 'Tonic & Club Soda');
INSERT INTO Categories VALUES (231, 'Fruit & Berry Soda');
INSERT INTO Categories VALUES (232, 'Ginger Ale');
INSERT INTO Categories VALUES (233, 'Orange Soda');
INSERT INTO Categories VALUES (234, 'Root Beer & Cream Soda');
INSERT INTO Categories VALUES (235, 'Spicy Cherry Soda');
INSERT INTO Categories VALUES (236, 'Tea Bags');
INSERT INTO Categories VALUES (237, 'Iced Tea');
INSERT INTO Categories VALUES (238, 'Tea Pods');
INSERT INTO Categories VALUES (239, 'Chai Tea');
INSERT INTO Categories VALUES (240, 'Cider Mix');
INSERT INTO Categories VALUES (241, 'Sparkling & Seltzer');
INSERT INTO Categories VALUES (242, 'Still Water');
INSERT INTO Categories VALUES (243, 'Enhanced Water');
INSERT INTO Categories VALUES (249, 'Milk Mix');
INSERT INTO Categories VALUES (250, 'Cakes');
INSERT INTO Categories VALUES (251, 'Cupcakes');
INSERT INTO Categories VALUES (252, 'Ice Cream Cakes');
INSERT INTO Categories VALUES (253, 'Cookies & Brownies');
INSERT INTO Categories VALUES (254, 'Bakery Snacks');
INSERT INTO Categories VALUES (255, 'Cheesecake & Cream Cakes');
INSERT INTO Categories VALUES (256, 'Pies, Tarts & Cobblers');
INSERT INTO Categories VALUES (257, 'Cream Desserts');
INSERT INTO Categories VALUES (259, 'Pastries & Croissants');
INSERT INTO Categories VALUES (260, 'Donuts');
INSERT INTO Categories VALUES (261, 'English Muffins');
INSERT INTO Categories VALUES (262, 'Coffee Cake');
INSERT INTO Categories VALUES (263, 'Breakfast Loaves');
INSERT INTO Categories VALUES (264, 'Dinner Rolls');
INSERT INTO Categories VALUES (265, 'Hamburger Buns');
INSERT INTO Categories VALUES (266, 'Sandwich Rolls');
INSERT INTO Categories VALUES (267, 'Hot Dog Buns');
INSERT INTO Categories VALUES (268, 'Sandwich Bread');
INSERT INTO Categories VALUES (269, 'Bagels');
INSERT INTO Categories VALUES (270, 'Muffins & Scones');
INSERT INTO Categories VALUES (271, 'Flatbread & Pita Bread');
INSERT INTO Categories VALUES (272, 'Breadsticks');
INSERT INTO Categories VALUES (275, 'Oatmeal & Hot Cereal');
INSERT INTO Categories VALUES (276, 'Granola & Muesli');
INSERT INTO Categories VALUES (277, 'Cereal - Natural/Organic');
INSERT INTO Categories VALUES (278, 'Waffles');
INSERT INTO Categories VALUES (279, 'Breakfast Entrees');
INSERT INTO Categories VALUES (280, 'Breakfast Sandwiches');
INSERT INTO Categories VALUES (281, 'Breakfast Burritos');
INSERT INTO Categories VALUES (685, 'Breakfast Sausage');
INSERT INTO Categories VALUES (283, 'Pancakes & French Toast');
INSERT INTO Categories VALUES (284, 'Pastries');
INSERT INTO Categories VALUES (285, 'Hash Browns');
INSERT INTO Categories VALUES (286, 'Muffins & Bagels');
INSERT INTO Categories VALUES (287, 'Granola Bars');
INSERT INTO Categories VALUES (288, 'Cereal Bars & Bites');
INSERT INTO Categories VALUES (289, 'Fruit & Grain Bars');
INSERT INTO Categories VALUES (291, 'Syrups');
INSERT INTO Categories VALUES (294, 'Canned Soups');
INSERT INTO Categories VALUES (295, 'Condensed Soups');
INSERT INTO Categories VALUES (296, 'Instant Ramen & Noodles');
INSERT INTO Categories VALUES (297, 'Ramen & Noodles');
INSERT INTO Categories VALUES (298, 'Soup Mix & Meals');
INSERT INTO Categories VALUES (299, 'Instant Soup & Meals');
INSERT INTO Categories VALUES (300, 'Corn & Baby Corn');
INSERT INTO Categories VALUES (301, 'Green Beans');
INSERT INTO Categories VALUES (302, 'Peas');
INSERT INTO Categories VALUES (303, 'Peppers & Green Chiles');
INSERT INTO Categories VALUES (574, 'Mushrooms');
INSERT INTO Categories VALUES (583, 'Artichokes');
INSERT INTO Categories VALUES (306, 'Mixed Vegetables');
INSERT INTO Categories VALUES (307, 'Beets');
INSERT INTO Categories VALUES (308, 'Potatoes');
INSERT INTO Categories VALUES (577, 'Carrots');
INSERT INTO Categories VALUES (310, 'Water Chestnuts');
INSERT INTO Categories VALUES (584, 'Asparagus');
INSERT INTO Categories VALUES (647, 'Lima & Butter Beans');
INSERT INTO Categories VALUES (313, 'Sweet Potatoes & Yams');
INSERT INTO Categories VALUES (314, 'Hominy');
INSERT INTO Categories VALUES (315, 'Sauerkraut');
INSERT INTO Categories VALUES (316, 'Bamboo Shoots');
INSERT INTO Categories VALUES (317, 'Greens & Collard Greens');
INSERT INTO Categories VALUES (318, 'Heart Of Palm');
INSERT INTO Categories VALUES (319, 'Spinach');
INSERT INTO Categories VALUES (320, 'Tuna');
INSERT INTO Categories VALUES (321, 'Sardines');
INSERT INTO Categories VALUES (322, 'Salmon');
INSERT INTO Categories VALUES (323, 'Clams & Clam Juice');
INSERT INTO Categories VALUES (324, 'Anchovies');
INSERT INTO Categories VALUES (325, 'Crab');
INSERT INTO Categories VALUES (326, 'Oysters');
INSERT INTO Categories VALUES (327, 'Shrimp');
INSERT INTO Categories VALUES (328, 'Baked Beans');
INSERT INTO Categories VALUES (329, 'Refried Beans');
INSERT INTO Categories VALUES (643, 'Black Beans');
INSERT INTO Categories VALUES (644, 'Pinto Beans');
INSERT INTO Categories VALUES (332, 'Kidney Beans');
INSERT INTO Categories VALUES (650, 'Garbanzo Beans');
INSERT INTO Categories VALUES (334, 'Chili Beans');
INSERT INTO Categories VALUES (645, 'Navy & White Beans');
INSERT INTO Categories VALUES (336, 'Cannellini Beans');
INSERT INTO Categories VALUES (337, 'Ranch Style Beans');
INSERT INTO Categories VALUES (338, 'Pork & Beans');
INSERT INTO Categories VALUES (339, 'Diced Tomatoes');
INSERT INTO Categories VALUES (340, 'Sliced & Whole Tomatoes');
INSERT INTO Categories VALUES (341, 'Tomato Sauce & Puree');
INSERT INTO Categories VALUES (342, 'Tomato Paste');
INSERT INTO Categories VALUES (343, 'Crushed Tomatoes');
INSERT INTO Categories VALUES (344, 'Sundried Tomatoes');
INSERT INTO Categories VALUES (479, 'Applesauce');
INSERT INTO Categories VALUES (346, 'Peaches');
INSERT INTO Categories VALUES (347, 'Pineapple');
INSERT INTO Categories VALUES (348, 'Fruit Cocktail');
INSERT INTO Categories VALUES (594, 'Pears');
INSERT INTO Categories VALUES (350, 'Mandarin Oranges');
INSERT INTO Categories VALUES (351, 'Maraschino Cherries');
INSERT INTO Categories VALUES (352, 'Cranberries');
INSERT INTO Categories VALUES (353, 'Apricots');
INSERT INTO Categories VALUES (591, 'Tropical Fruit');
INSERT INTO Categories VALUES (355, 'Mixed Fruit');
INSERT INTO Categories VALUES (356, 'Prunes');
INSERT INTO Categories VALUES (357, 'Broth & Stocks');
INSERT INTO Categories VALUES (358, 'Bouillon & Base');
INSERT INTO Categories VALUES (359, 'Chili');
INSERT INTO Categories VALUES (361, 'Hash');
INSERT INTO Categories VALUES (362, 'Sloppy Joe');
INSERT INTO Categories VALUES (363, 'Stew');
INSERT INTO Categories VALUES (365, 'Luncheon Meat');
INSERT INTO Categories VALUES (367, 'Pate & Spreads');
INSERT INTO Categories VALUES (368, 'Vienna Sausages');
INSERT INTO Categories VALUES (369, 'Herbs & Spices');
INSERT INTO Categories VALUES (370, 'Seasonings & Blends');
INSERT INTO Categories VALUES (371, 'Pepper & Peppercorns');
INSERT INTO Categories VALUES (372, 'Salt');
INSERT INTO Categories VALUES (373, 'Onion & Garlic');
INSERT INTO Categories VALUES (374, 'Dry Mixes');
INSERT INTO Categories VALUES (375, 'Barbecue Sauce');
INSERT INTO Categories VALUES (376, 'Meat & Steak Sauce');
INSERT INTO Categories VALUES (377, 'Hot Sauce');
INSERT INTO Categories VALUES (378, 'Marinades');
INSERT INTO Categories VALUES (379, 'Gravy & Glazes');
INSERT INTO Categories VALUES (380, 'Seafood Sauces');
INSERT INTO Categories VALUES (381, 'Bread Coatings & Batters');
INSERT INTO Categories VALUES (382, 'Horseradish');
INSERT INTO Categories VALUES (383, 'Bottled Dressings');
INSERT INTO Categories VALUES (384, 'Chilled Dressing');
INSERT INTO Categories VALUES (385, 'Croutons & Toppings');
INSERT INTO Categories VALUES (386, 'Dressing Mix');
INSERT INTO Categories VALUES (387, 'Peanut Butter & Spreads');
INSERT INTO Categories VALUES (388, 'Jams, Jelly & Spreads');
INSERT INTO Categories VALUES (389, 'Mayonnaise');
INSERT INTO Categories VALUES (390, 'Mustard');
INSERT INTO Categories VALUES (391, 'Ketchup');
INSERT INTO Categories VALUES (392, 'Sandwich Spreads');
INSERT INTO Categories VALUES (393, 'Flour');
INSERT INTO Categories VALUES (394, 'Nuts & Seeds');
INSERT INTO Categories VALUES (395, 'Chocolate & Baking Chips');
INSERT INTO Categories VALUES (396, 'Sugar');
INSERT INTO Categories VALUES (397, 'Sweeteners & Substitutes');
INSERT INTO Categories VALUES (398, 'Baking Extracts');
INSERT INTO Categories VALUES (399, 'Powdered & Canned Milk');
INSERT INTO Categories VALUES (400, 'Coconut Flakes & Milk');
INSERT INTO Categories VALUES (401, 'Corn Meal & Polenta');
INSERT INTO Categories VALUES (402, 'Baking Soda & Powder');
INSERT INTO Categories VALUES (403, 'Chocolate Baking Bars');
INSERT INTO Categories VALUES (404, 'Yeast');
INSERT INTO Categories VALUES (405, 'Marshmallows');
INSERT INTO Categories VALUES (406, 'Cocoa & Carob Powder');
INSERT INTO Categories VALUES (407, 'Syrups & Molasses');
INSERT INTO Categories VALUES (408, 'Cake Mix');
INSERT INTO Categories VALUES (409, 'Rolls & Pastry Dough');
INSERT INTO Categories VALUES (410, 'Gelatin & Jello Mix');
INSERT INTO Categories VALUES (411, 'Pudding & Mousse');
INSERT INTO Categories VALUES (412, 'Brownies & Bar Mix');
INSERT INTO Categories VALUES (413, 'Muffin Mix');
INSERT INTO Categories VALUES (414, 'Cookie Dough');
INSERT INTO Categories VALUES (415, 'Cookie Mix');
INSERT INTO Categories VALUES (416, 'Pie Crust & Pastry Shell');
INSERT INTO Categories VALUES (417, 'Bread Mix');
INSERT INTO Categories VALUES (418, 'Pie Filling');
INSERT INTO Categories VALUES (419, 'Dessert Decorations');
INSERT INTO Categories VALUES (420, 'Toppings');
INSERT INTO Categories VALUES (421, 'Frosting');
INSERT INTO Categories VALUES (422, 'Canning Supplies');
INSERT INTO Categories VALUES (423, 'Ice Cream Cones & Cups');
INSERT INTO Categories VALUES (424, 'Cupcake Liners & Cups');
INSERT INTO Categories VALUES (425, 'Food Coloring');
INSERT INTO Categories VALUES (426, 'Olive Oil');
INSERT INTO Categories VALUES (427, 'Vinegar');
INSERT INTO Categories VALUES (428, 'Specialty Oil');
INSERT INTO Categories VALUES (429, 'Cooking Oil');
INSERT INTO Categories VALUES (430, 'Cooking Sprays');
INSERT INTO Categories VALUES (431, 'Shortening');
INSERT INTO Categories VALUES (432, 'Pickles');
INSERT INTO Categories VALUES (433, 'Olives - Specialty');
INSERT INTO Categories VALUES (434, 'Olives');
INSERT INTO Categories VALUES (575, 'Peppers');
INSERT INTO Categories VALUES (436, 'Marinated Vegetables');
INSERT INTO Categories VALUES (437, 'Relish & Chutney');
INSERT INTO Categories VALUES (438, 'Honey & Agave Nectar');
INSERT INTO Categories VALUES (439, 'Potato Chips & Crisps');
INSERT INTO Categories VALUES (440, 'Tortilla Chips');
INSERT INTO Categories VALUES (461, 'Variety & Multipacks');
INSERT INTO Categories VALUES (442, 'Cheese & Puffed Snacks');
INSERT INTO Categories VALUES (443, 'Multi-Grain Chips');
INSERT INTO Categories VALUES (444, 'Pita & Bagel Chips');
INSERT INTO Categories VALUES (445, 'Fruit & Vegetable Chips');
INSERT INTO Categories VALUES (446, 'Pork Rinds');
INSERT INTO Categories VALUES (447, 'Snack Mixes');
INSERT INTO Categories VALUES (448, 'Corn Chips');
INSERT INTO Categories VALUES (449, 'Onion Rings');
INSERT INTO Categories VALUES (452, 'Sandwich Cookies');
INSERT INTO Categories VALUES (453, 'Graham Crackers');
INSERT INTO Categories VALUES (454, 'Biscotti');
INSERT INTO Categories VALUES (455, 'Wafer Cookies');
INSERT INTO Categories VALUES (457, 'Cheese Crackers');
INSERT INTO Categories VALUES (458, 'Classic Crackers');
INSERT INTO Categories VALUES (459, 'Deli & Water Crackers');
INSERT INTO Categories VALUES (460, 'Wheat Crackers');
INSERT INTO Categories VALUES (462, 'Saltines');
INSERT INTO Categories VALUES (463, 'Rice Crackers');
INSERT INTO Categories VALUES (464, 'Sandwich Crackers');
INSERT INTO Categories VALUES (466, 'Christmas Candy');
INSERT INTO Categories VALUES (467, 'Halloween Candy');
INSERT INTO Categories VALUES (468, 'Easter Candy');
INSERT INTO Categories VALUES (469, 'Valentine Candy');
INSERT INTO Categories VALUES (470, 'Salsa');
INSERT INTO Categories VALUES (471, 'Cheese & Queso Dip');
INSERT INTO Categories VALUES (472, 'Ranch & Onion Dip');
INSERT INTO Categories VALUES (473, 'Bean Dip');
INSERT INTO Categories VALUES (474, 'Nuts');
INSERT INTO Categories VALUES (475, 'Seeds');
INSERT INTO Categories VALUES (476, 'Trail Mix');
INSERT INTO Categories VALUES (478, 'Fruit Cups & Pouches');
INSERT INTO Categories VALUES (480, 'Jerky');
INSERT INTO Categories VALUES (484, 'Pudding');
INSERT INTO Categories VALUES (485, 'Gelatin');
INSERT INTO Categories VALUES (486, 'Yogurt');
INSERT INTO Categories VALUES (487, 'Greek Yogurt');
INSERT INTO Categories VALUES (488, 'Probiotic Yogurt & Kefir');
INSERT INTO Categories VALUES (490, 'Kids Yogurt');
INSERT INTO Categories VALUES (491, 'Sandwich Cheese');
INSERT INTO Categories VALUES (492, 'Shredded Cheese');
INSERT INTO Categories VALUES (493, 'Loaf & Block Cheese');
INSERT INTO Categories VALUES (494, 'Cream Cheese');
INSERT INTO Categories VALUES (495, 'String & Snack Cheese');
INSERT INTO Categories VALUES (496, 'Cottage Cheese');
INSERT INTO Categories VALUES (497, 'Grated & Topping Cheese');
INSERT INTO Categories VALUES (498, 'Ricotta & Mozzarella');
INSERT INTO Categories VALUES (499, 'Spread/Processed Cheese');
INSERT INTO Categories VALUES (500, 'Coffee Creamer');
INSERT INTO Categories VALUES (501, 'Milk Alternatives');
INSERT INTO Categories VALUES (502, 'Milk');
INSERT INTO Categories VALUES (503, 'Milk - Flavored');
INSERT INTO Categories VALUES (504, 'Milk - Lactose Free');
INSERT INTO Categories VALUES (505, 'Half & Half');
INSERT INTO Categories VALUES (506, 'Whipping Cream');
INSERT INTO Categories VALUES (507, 'Eggnog');
INSERT INTO Categories VALUES (508, 'Buttermilk');
INSERT INTO Categories VALUES (509, 'Butter');
INSERT INTO Categories VALUES (510, 'Margarine & Spreads');
INSERT INTO Categories VALUES (511, 'Sour Cream');
INSERT INTO Categories VALUES (513, 'Egg Substitute');
INSERT INTO Categories VALUES (700, 'Turkey');
INSERT INTO Categories VALUES (515, 'Salami & Sausage');
INSERT INTO Categories VALUES (703, 'Ham');
INSERT INTO Categories VALUES (680, 'Variety Meats');
INSERT INTO Categories VALUES (698, 'Chicken');
INSERT INTO Categories VALUES (520, 'Deli Side Dishes & Meals');
INSERT INTO Categories VALUES (522, 'Deli Salads Green');
INSERT INTO Categories VALUES (523, 'Deli Condiments');
INSERT INTO Categories VALUES (524, 'Deli Olives');
INSERT INTO Categories VALUES (525, 'Deli Pates & Mousse');
INSERT INTO Categories VALUES (526, 'Kosher Deli');
INSERT INTO Categories VALUES (527, 'Deli Style Hummus');
INSERT INTO Categories VALUES (528, 'Deli Style Dips');
INSERT INTO Categories VALUES (529, 'Deli Style Guacamole');
INSERT INTO Categories VALUES (532, 'Deli Snack Packs');
INSERT INTO Categories VALUES (535, 'Frozen Meals');
INSERT INTO Categories VALUES (536, 'Frozen Meals Wellness');
INSERT INTO Categories VALUES (537, 'Frozen Meals Multi-Serve');
INSERT INTO Categories VALUES (538, 'Frozen Pizza Multi-Serve');
INSERT INTO Categories VALUES (539, 'Frozen Meals Organic/Veg');
INSERT INTO Categories VALUES (540, 'Frozen Bread & Bakery');
INSERT INTO Categories VALUES (541, 'Frozen Pizza');
INSERT INTO Categories VALUES (542, 'Frozen Pasta & Sauce');
INSERT INTO Categories VALUES (543, 'Ice Cream');
INSERT INTO Categories VALUES (544, 'Novelty Ice Cream & Bars');
INSERT INTO Categories VALUES (545, 'Popsicles & Fruit Bars');
INSERT INTO Categories VALUES (546, 'Gelato');
INSERT INTO Categories VALUES (547, 'Sherbet & Sorbet');
INSERT INTO Categories VALUES (548, 'Frozen Yogurt');
INSERT INTO Categories VALUES (550, 'Frozen Potatoes & Onions');
INSERT INTO Categories VALUES (551, 'Traditional Appetizers');
INSERT INTO Categories VALUES (552, 'Mexican Appetizers');
INSERT INTO Categories VALUES (553, 'Pockets & Sandwiches');
INSERT INTO Categories VALUES (554, 'Pizza & Corn Dogs');
INSERT INTO Categories VALUES (555, 'Asian Appetizers');
INSERT INTO Categories VALUES (556, 'Frozen Pies & Desserts');
INSERT INTO Categories VALUES (557, 'Frozen Fruit & Berries');
INSERT INTO Categories VALUES (558, 'Frozen Pastry Dough');
INSERT INTO Categories VALUES (559, 'Frozen Whipped Toppings');
INSERT INTO Categories VALUES (560, 'Frozen Juices');
INSERT INTO Categories VALUES (561, 'Ice');
INSERT INTO Categories VALUES (562, 'Packaged Vegetables');
INSERT INTO Categories VALUES (563, 'Packaged Fresh Fruit');
INSERT INTO Categories VALUES (564, 'Packaged Salads');
INSERT INTO Categories VALUES (565, 'Tofu & Meat Alternatives');
INSERT INTO Categories VALUES (566, 'Packaged Dips & Mix');
INSERT INTO Categories VALUES (567, 'Herbs');
INSERT INTO Categories VALUES (568, 'Specialty Vegetables');
INSERT INTO Categories VALUES (569, 'Potatoes & Yams');
INSERT INTO Categories VALUES (570, 'Lettuce & Greens');
INSERT INTO Categories VALUES (571, 'Onions & Garlic');
INSERT INTO Categories VALUES (572, 'Squash');
INSERT INTO Categories VALUES (573, 'Tomatoes');
INSERT INTO Categories VALUES (576, 'Radishes & Roots');
INSERT INTO Categories VALUES (578, 'Beans & Peas');
INSERT INTO Categories VALUES (579, 'Cabbages');
INSERT INTO Categories VALUES (580, 'Broccoli & Cauliflower');
INSERT INTO Categories VALUES (581, 'Cucumbers');
INSERT INTO Categories VALUES (582, 'Celery');
INSERT INTO Categories VALUES (585, 'Brussels Sprouts');
INSERT INTO Categories VALUES (586, 'Corn');
INSERT INTO Categories VALUES (587, 'Dried Fruits');
INSERT INTO Categories VALUES (588, 'Nuts, Seeds & Snacks');
INSERT INTO Categories VALUES (589, 'Dried Vegetables');
INSERT INTO Categories VALUES (590, 'Apples');
INSERT INTO Categories VALUES (592, 'Citrus');
INSERT INTO Categories VALUES (593, 'Berries');
INSERT INTO Categories VALUES (595, 'Grapes');
INSERT INTO Categories VALUES (596, 'Melons');
INSERT INTO Categories VALUES (597, 'Avocados');
INSERT INTO Categories VALUES (598, 'Seasonal & Stone Fruit');
INSERT INTO Categories VALUES (599, 'Bananas');
INSERT INTO Categories VALUES (600, 'Marinara Pasta Sauce');
INSERT INTO Categories VALUES (601, 'Alfredo Sauce');
INSERT INTO Categories VALUES (602, 'Vegetable Pasta Sauce');
INSERT INTO Categories VALUES (603, 'Pesto');
INSERT INTO Categories VALUES (604, 'Cheese Pasta Sauce');
INSERT INTO Categories VALUES (605, 'Meat Pasta Sauce');
INSERT INTO Categories VALUES (606, 'Vodka Pasta Sauce');
INSERT INTO Categories VALUES (607, 'Angel Hair & Spaghetti');
INSERT INTO Categories VALUES (608, 'Tortellini & Ravioli');
INSERT INTO Categories VALUES (609, 'Penne');
INSERT INTO Categories VALUES (610, 'Rotini & Spirals');
INSERT INTO Categories VALUES (611, 'Macaroni & Ditalini');
INSERT INTO Categories VALUES (612, 'Egg Noodles');
INSERT INTO Categories VALUES (613, 'Fettuccine');
INSERT INTO Categories VALUES (614, 'Lasagne & Manicotti');
INSERT INTO Categories VALUES (615, 'Linguine');
INSERT INTO Categories VALUES (616, 'Shells & Orecchiette');
INSERT INTO Categories VALUES (617, 'Rigatoni');
INSERT INTO Categories VALUES (618, 'Farfalle & Bowtie');
INSERT INTO Categories VALUES (619, 'Couscous');
INSERT INTO Categories VALUES (620, 'Orzo');
INSERT INTO Categories VALUES (621, 'Rice Sides');
INSERT INTO Categories VALUES (622, 'Quinoa Sides');
INSERT INTO Categories VALUES (623, 'Couscous Sides');
INSERT INTO Categories VALUES (624, 'Risotto Sides');
INSERT INTO Categories VALUES (625, 'Macaroni & Cheese Boxed');
INSERT INTO Categories VALUES (626, 'Macaroni & Cheese Cups');
INSERT INTO Categories VALUES (627, 'Instant Rice');
INSERT INTO Categories VALUES (628, 'White Rice');
INSERT INTO Categories VALUES (629, 'Jasmine Rice');
INSERT INTO Categories VALUES (630, 'Basmati Rice');
INSERT INTO Categories VALUES (631, 'Calrose Rice');
INSERT INTO Categories VALUES (632, 'Brown Rice');
INSERT INTO Categories VALUES (633, 'Arborio Rice');
INSERT INTO Categories VALUES (634, 'Sushi Rice');
INSERT INTO Categories VALUES (635, 'Specialty Rice');
INSERT INTO Categories VALUES (636, 'Wild Rice & Blends');
INSERT INTO Categories VALUES (637, 'Mashed Potatoes');
INSERT INTO Categories VALUES (638, 'Au Gratin & Scalloped');
INSERT INTO Categories VALUES (639, 'Gnocchi & Dumplings');
INSERT INTO Categories VALUES (640, 'Skillet Dinners');
INSERT INTO Categories VALUES (641, 'Simmer & Cooking Sauces');
INSERT INTO Categories VALUES (642, 'Lentils & Peas');
INSERT INTO Categories VALUES (646, 'Kidney & Red Beans');
INSERT INTO Categories VALUES (648, 'Variety & Mixed Beans');
INSERT INTO Categories VALUES (649, 'Black Eyed Peas');
INSERT INTO Categories VALUES (651, 'Pasta Sides');
INSERT INTO Categories VALUES (652, 'Pizza Crust & Kits');
INSERT INTO Categories VALUES (653, 'Pizza Sauce');
INSERT INTO Categories VALUES (655, 'Quinoa');
INSERT INTO Categories VALUES (656, 'Variety Grains');
INSERT INTO Categories VALUES (657, 'Barley');
INSERT INTO Categories VALUES (658, 'Tortillas, Tacos & Wraps');
INSERT INTO Categories VALUES (659, 'Sauces');
INSERT INTO Categories VALUES (660, 'Hispanic Specialty');
INSERT INTO Categories VALUES (662, 'Peppers & Chilis');
INSERT INTO Categories VALUES (663, 'Sauces, Oils & Spices');
INSERT INTO Categories VALUES (664, 'Asian Specialty Foods');
INSERT INTO Categories VALUES (665, 'Snacks');
INSERT INTO Categories VALUES (666, 'Soups, Meals & Bowls');
INSERT INTO Categories VALUES (667, 'Noodles & Rice');
INSERT INTO Categories VALUES (669, 'Indian Middle East Foods');
INSERT INTO Categories VALUES (670, 'Southern Foods');
INSERT INTO Categories VALUES (671, 'Caribbean Foods');
INSERT INTO Categories VALUES (672, 'Eastern European Foods');
INSERT INTO Categories VALUES (673, 'Italian Foods');
INSERT INTO Categories VALUES (674, 'Mediterranean Foods');
INSERT INTO Categories VALUES (675, 'Beef Steaks');
INSERT INTO Categories VALUES (676, 'Beef Whole Cuts & Roasts');
INSERT INTO Categories VALUES (677, 'Ground Beef');
INSERT INTO Categories VALUES (678, 'Beef Strips & Cubes');
INSERT INTO Categories VALUES (679, 'Beef Ribs');
INSERT INTO Categories VALUES (681, 'Smoked & Cured Beef');
INSERT INTO Categories VALUES (682, 'Dinner Sausage');
INSERT INTO Categories VALUES (683, 'Bacon');
INSERT INTO Categories VALUES (684, 'Hot Dogs & Franks');
INSERT INTO Categories VALUES (686, 'Lunch Meat');
INSERT INTO Categories VALUES (687, 'Lunch Packs');
INSERT INTO Categories VALUES (688, 'Salami & Pepperoni');
INSERT INTO Categories VALUES (690, 'Seafood');
INSERT INTO Categories VALUES (693, 'Fish');
INSERT INTO Categories VALUES (694, 'Shrimp & Prawns');
INSERT INTO Categories VALUES (695, 'Oyster, Clams & Scallops');
INSERT INTO Categories VALUES (696, 'Lobster & Crab');
INSERT INTO Categories VALUES (697, 'Smoked & Cured Fish');
INSERT INTO Categories VALUES (699, 'Turkey - Whole');
INSERT INTO Categories VALUES (701, 'Game Hens & Fowl');
INSERT INTO Categories VALUES (702, 'Pork Chops & Steaks');
INSERT INTO Categories VALUES (704, 'Pork Roasts & Tenderloin');
INSERT INTO Categories VALUES (705, 'Pork Ribs');
INSERT INTO Categories VALUES (706, 'Pork Ground or Strips');
INSERT INTO Categories VALUES (707, 'Pork Variety Meat & Lard');
INSERT INTO Categories VALUES (709, 'Paper Towels');
INSERT INTO Categories VALUES (710, 'Bath Tissue');
INSERT INTO Categories VALUES (711, 'Facial Tissue');
INSERT INTO Categories VALUES (712, 'Moist Wipes');
INSERT INTO Categories VALUES (713, 'Napkins');
INSERT INTO Categories VALUES (714, 'Office & School Supplies');
INSERT INTO Categories VALUES (715, 'Batteries');
INSERT INTO Categories VALUES (716, 'Light Bulbs');
INSERT INTO Categories VALUES (717, 'Shoe Care');
INSERT INTO Categories VALUES (718, 'Automotive');
INSERT INTO Categories VALUES (719, 'Pest Control');
INSERT INTO Categories VALUES (720, 'Miscellaneous Household');
INSERT INTO Categories VALUES (721, 'Hardware');
INSERT INTO Categories VALUES (722, 'Flashlights & Electrical');
INSERT INTO Categories VALUES (723, 'Pool & Spa Care');
INSERT INTO Categories VALUES (724, 'Gadgets & Utensils');
INSERT INTO Categories VALUES (725, 'Ovenware');
INSERT INTO Categories VALUES (726, 'Ovenware - Foil');
INSERT INTO Categories VALUES (727, 'Cookware');
INSERT INTO Categories VALUES (728, 'Water Filtration');
INSERT INTO Categories VALUES (729, 'Sweepers & Supplies');
INSERT INTO Categories VALUES (730, 'All Purpose Cleaners');
INSERT INTO Categories VALUES (731, 'Bathroom & Toilet');
INSERT INTO Categories VALUES (732, 'Carpet & Floor Care');
INSERT INTO Categories VALUES (733, 'Furniture Care');
INSERT INTO Categories VALUES (734, 'Disinfectant Sprays');
INSERT INTO Categories VALUES (735, 'Glass Cleaners');
INSERT INTO Categories VALUES (736, 'Drain & Septic Care');
INSERT INTO Categories VALUES (737, 'Specialty Surface Care');
INSERT INTO Categories VALUES (738, 'Rock Salt & Softeners');
INSERT INTO Categories VALUES (739, 'Candles');
INSERT INTO Categories VALUES (740, 'Electric');
INSERT INTO Categories VALUES (741, 'Solid & Liquid');
INSERT INTO Categories VALUES (742, 'Sprays');
INSERT INTO Categories VALUES (743, 'Laundry Detergent');
INSERT INTO Categories VALUES (744, 'Fabric Softener');
INSERT INTO Categories VALUES (745, 'Stain Remover & Boosters');
INSERT INTO Categories VALUES (746, 'Bleach');
INSERT INTO Categories VALUES (747, 'Scent & Deodorizer');
INSERT INTO Categories VALUES (748, 'Starch & Laundry Needs');
INSERT INTO Categories VALUES (749, 'Storage Containers');
INSERT INTO Categories VALUES (750, 'Plastic Bags');
INSERT INTO Categories VALUES (751, 'Storage Containers-Disp');
INSERT INTO Categories VALUES (752, 'Foil');
INSERT INTO Categories VALUES (753, 'Steam & Cooking Bags');
INSERT INTO Categories VALUES (754, 'Freezer & Wax Paper');
INSERT INTO Categories VALUES (755, 'Plastic Wrap');
INSERT INTO Categories VALUES (756, 'Trash Bags');
INSERT INTO Categories VALUES (757, 'Plates & Bowls');
INSERT INTO Categories VALUES (758, 'Cups & Glasses');
INSERT INTO Categories VALUES (759, 'Cutlery');
INSERT INTO Categories VALUES (760, 'Tableware Essentials');
INSERT INTO Categories VALUES (761, 'Dish Washing Liquid');
INSERT INTO Categories VALUES (762, 'Dishwasher Detergents');
INSERT INTO Categories VALUES (763, 'Dishwasher Additives');
INSERT INTO Categories VALUES (764, 'Charcoal & Smoking Chips');
INSERT INTO Categories VALUES (765, 'Matches & Lighters');
INSERT INTO Categories VALUES (766, 'Fire Logs');
INSERT INTO Categories VALUES (767, 'Lighter Fluid');
INSERT INTO Categories VALUES (768, 'Cosmetics');
INSERT INTO Categories VALUES (769, 'Hand & Body Lotion');
INSERT INTO Categories VALUES (770, 'Body Wash');
INSERT INTO Categories VALUES (771, 'Facial Cleansers');
INSERT INTO Categories VALUES (772, 'Liquid Soap');
INSERT INTO Categories VALUES (773, 'Facial Treatments');
INSERT INTO Categories VALUES (774, 'Lip Care');
INSERT INTO Categories VALUES (775, 'Bar Soap');
INSERT INTO Categories VALUES (776, 'Sun Block');
INSERT INTO Categories VALUES (777, 'Facial Acne Treatments');
INSERT INTO Categories VALUES (778, 'Facial Moisturizers');
INSERT INTO Categories VALUES (779, 'Hand Sanitizer');
INSERT INTO Categories VALUES (780, 'Bath Care & Needs');
INSERT INTO Categories VALUES (781, 'After Bath Products');
INSERT INTO Categories VALUES (782, 'Mens Skin Care');
INSERT INTO Categories VALUES (783, 'Cotton Balls & Swabs');
INSERT INTO Categories VALUES (784, 'Hair Color & Perms');
INSERT INTO Categories VALUES (785, 'Performance Shampoo Cond');
INSERT INTO Categories VALUES (786, 'Hair Accessories');
INSERT INTO Categories VALUES (787, 'Kids & Family');
INSERT INTO Categories VALUES (788, 'Professional');
INSERT INTO Categories VALUES (789, 'Performance Styling');
INSERT INTO Categories VALUES (790, 'Natural & Organic');
INSERT INTO Categories VALUES (791, 'Dandruff & Therapeutic');
INSERT INTO Categories VALUES (792, 'Premium & Salon Inspired');
INSERT INTO Categories VALUES (793, 'Hair Growth');
INSERT INTO Categories VALUES (794, 'Multi Vitamins');
INSERT INTO Categories VALUES (795, 'Supplements');
INSERT INTO Categories VALUES (796, 'Herbal Supplements');
INSERT INTO Categories VALUES (797, 'Vitamins');
INSERT INTO Categories VALUES (798, 'Minerals');
INSERT INTO Categories VALUES (799, 'Toothpaste');
INSERT INTO Categories VALUES (800, 'Oral Rinse & Mouthwash');
INSERT INTO Categories VALUES (801, 'Toothbrush');
INSERT INTO Categories VALUES (802, 'Dental Floss');
INSERT INTO Categories VALUES (803, 'Toothbrush Powered');
INSERT INTO Categories VALUES (805, 'Denture Care');
INSERT INTO Categories VALUES (806, 'At Home Whitening');
INSERT INTO Categories VALUES (807, 'Cough & Cold');
INSERT INTO Categories VALUES (808, 'Allergy - Adult');
INSERT INTO Categories VALUES (809, 'Cough & Cold Pediatric');
INSERT INTO Categories VALUES (810, 'Cough & Throat Relief');
INSERT INTO Categories VALUES (811, 'Nasal & Snoring Relief');
INSERT INTO Categories VALUES (812, 'Allergy - Pediatric');
INSERT INTO Categories VALUES (813, 'Thermometers');
INSERT INTO Categories VALUES (814, 'Asthma & Bronchial');
INSERT INTO Categories VALUES (815, 'Sport Nutrition & Energy');
INSERT INTO Categories VALUES (816, 'Lifestyle Nutrition');
INSERT INTO Categories VALUES (817, 'Active Health Management');
INSERT INTO Categories VALUES (818, 'Weight Management');
INSERT INTO Categories VALUES (819, 'Diabetes Management');
INSERT INTO Categories VALUES (820, 'Acid Neutralizers');
INSERT INTO Categories VALUES (821, 'Laxative Treatments');
INSERT INTO Categories VALUES (822, 'Fiber Regimen');
INSERT INTO Categories VALUES (823, 'Probiotics');
INSERT INTO Categories VALUES (824, 'Gas Relief');
INSERT INTO Categories VALUES (825, 'Proton Pump Inhibitors');
INSERT INTO Categories VALUES (826, 'Acid Blockers');
INSERT INTO Categories VALUES (827, 'Gastro Intestinal Relief');
INSERT INTO Categories VALUES (828, 'Anti Diarrhea');
INSERT INTO Categories VALUES (829, 'Hemorrhoid Treatments');
INSERT INTO Categories VALUES (830, 'Motion Sickness & Nausea');
INSERT INTO Categories VALUES (831, 'Digestive Pediatric');
INSERT INTO Categories VALUES (832, 'Lactose Intolerance');
INSERT INTO Categories VALUES (834, 'External Analgesics');
INSERT INTO Categories VALUES (835, 'Sleep Aids & Stimulants');
INSERT INTO Categories VALUES (836, 'Pain Relief Pediatric');
INSERT INTO Categories VALUES (837, 'First Aid');
INSERT INTO Categories VALUES (838, 'Skin Treatments');
INSERT INTO Categories VALUES (839, 'Alcohol & Peroxide');
INSERT INTO Categories VALUES (840, 'Medical Supplies');
INSERT INTO Categories VALUES (841, 'Pads');
INSERT INTO Categories VALUES (842, 'Tampons');
INSERT INTO Categories VALUES (843, 'Liners');
INSERT INTO Categories VALUES (844, 'Feminine Care & Medicine');
INSERT INTO Categories VALUES (845, 'Mens Deodorant');
INSERT INTO Categories VALUES (846, 'Womens Deodorant');
INSERT INTO Categories VALUES (847, 'Unisex Deodorant');
INSERT INTO Categories VALUES (848, 'Mens Body Spray');
INSERT INTO Categories VALUES (849, 'Eye Care');
INSERT INTO Categories VALUES (850, 'Contact Lens Care');
INSERT INTO Categories VALUES (851, 'Ear Care');
INSERT INTO Categories VALUES (852, 'Eye Accessories');
INSERT INTO Categories VALUES (853, 'Mens Shave Needs');
INSERT INTO Categories VALUES (854, 'Mens Razors/Cartridges');
INSERT INTO Categories VALUES (855, 'Mens Disposable Razor');
INSERT INTO Categories VALUES (856, 'Womens Disposable Razor');
INSERT INTO Categories VALUES (857, 'Womens Shave Needs');
INSERT INTO Categories VALUES (858, 'Womens Razors/Cartridges');
INSERT INTO Categories VALUES (859, 'Wax & Hair Removal');
INSERT INTO Categories VALUES (860, 'Odor & Antifungal');
INSERT INTO Categories VALUES (861, 'Insoles & Inserts');
INSERT INTO Categories VALUES (862, 'Corn, Callus & Wart Care');
INSERT INTO Categories VALUES (863, 'Grooming');
INSERT INTO Categories VALUES (865, 'Adult Care');
INSERT INTO Categories VALUES (866, 'Adult Care Accessories');
INSERT INTO Categories VALUES (867, 'Contraceptives');
INSERT INTO Categories VALUES (868, 'Intimacy Enhancement');
INSERT INTO Categories VALUES (869, 'Pregnancy Kits');
INSERT INTO Categories VALUES (870, 'Socks');
INSERT INTO Categories VALUES (871, 'Pantyhose & Knee Highs');
INSERT INTO Categories VALUES (872, 'Dog Snacks');
INSERT INTO Categories VALUES (873, 'Dog Food - Moist');
INSERT INTO Categories VALUES (874, 'Dog Food - Dry');
INSERT INTO Categories VALUES (875, 'Dog Supplies & Toys');
INSERT INTO Categories VALUES (876, 'Cat Food - Moist');
INSERT INTO Categories VALUES (877, 'Cat Food - Dry');
INSERT INTO Categories VALUES (878, 'Cat Snacks');
INSERT INTO Categories VALUES (879, 'Litter & Deodorant');
INSERT INTO Categories VALUES (880, 'Cat Supplies & Toys');
INSERT INTO Categories VALUES (881, 'Bird Care');
INSERT INTO Categories VALUES (882, 'Other Animal Care');
INSERT INTO Categories VALUES (883, 'Fish Care');
INSERT INTO Categories VALUES (884, 'Wine Blends & Other');
INSERT INTO Categories VALUES (885, 'Cabernet Sauvignon');
INSERT INTO Categories VALUES (886, 'Chardonnay');
INSERT INTO Categories VALUES (887, 'Pinot Noir');
INSERT INTO Categories VALUES (888, 'Sparkling Wine');
INSERT INTO Categories VALUES (889, 'Sauvignon & Fume Blanc');
INSERT INTO Categories VALUES (890, 'Pinot Grigio & Gris');
INSERT INTO Categories VALUES (891, 'Merlot');
INSERT INTO Categories VALUES (892, 'Zinfandel');
INSERT INTO Categories VALUES (893, 'Rose');
INSERT INTO Categories VALUES (894, 'Sweet & Flavored Wine');
INSERT INTO Categories VALUES (895, 'Port & Sherry');
INSERT INTO Categories VALUES (896, 'Malbec');
INSERT INTO Categories VALUES (897, 'Dessert Wine');
INSERT INTO Categories VALUES (898, 'Moscato & Muscat');
INSERT INTO Categories VALUES (899, 'Riesling');
INSERT INTO Categories VALUES (900, 'Sake & Rice Wine');
INSERT INTO Categories VALUES (901, 'Syrah & Shiraz');
INSERT INTO Categories VALUES (902, 'Gewurztraminer');
INSERT INTO Categories VALUES (903, 'Whiskey & Bourbon');
INSERT INTO Categories VALUES (904, 'Tequila & Mezcal');
INSERT INTO Categories VALUES (905, 'Vodka');
INSERT INTO Categories VALUES (906, 'Cocktails Ready To Drink');
INSERT INTO Categories VALUES (907, 'Cordials & Liqueur');
INSERT INTO Categories VALUES (908, 'Cocktail Mixes');
INSERT INTO Categories VALUES (909, 'Rum');
INSERT INTO Categories VALUES (910, 'Scotch');
INSERT INTO Categories VALUES (911, 'Gin');
INSERT INTO Categories VALUES (912, 'Cognac & Brandy');
INSERT INTO Categories VALUES (913, 'Vermouth');
INSERT INTO Categories VALUES (914, 'Craft Beer');
INSERT INTO Categories VALUES (915, 'Imported Beer');
INSERT INTO Categories VALUES (916, 'Domestic Beer');
INSERT INTO Categories VALUES (917, 'Spiked Seltzers');
INSERT INTO Categories VALUES (918, 'Flavored Malt Beverages');
INSERT INTO Categories VALUES (919, 'Cider');
INSERT INTO Categories VALUES (920, 'Non-Alcoholic Beer');
INSERT INTO Sites VALUES (0, 'vons.com', 'vons.com', 'vons.com', 'vons.com');
INSERT INTO Supplier_categories VALUES (19, 0, 19, 0);
INSERT INTO Supplier_categories VALUES (20, 0, 20, 0);
INSERT INTO Supplier_categories VALUES (21, 0, 21, 0);
INSERT INTO Supplier_categories VALUES (22, 0, 22, 0);
INSERT INTO Supplier_categories VALUES (23, 661, 23, 0);
INSERT INTO Supplier_categories VALUES (24, 661, 24, 0);
INSERT INTO Supplier_categories VALUES (25, 661, 25, 0);
INSERT INTO Supplier_categories VALUES (26, 661, 26, 0);
INSERT INTO Supplier_categories VALUES (27, 661, 27, 0);
INSERT INTO Supplier_categories VALUES (244, 661, 244, 0);
INSERT INTO Supplier_categories VALUES (245, 661, 245, 0);
INSERT INTO Supplier_categories VALUES (246, 661, 246, 0);
INSERT INTO Supplier_categories VALUES (247, 661, 247, 0);
INSERT INTO Supplier_categories VALUES (248, 661, 248, 0);
INSERT INTO Supplier_categories VALUES (33, 2, 33, 0);
INSERT INTO Supplier_categories VALUES (34, 2, 34, 0);
INSERT INTO Supplier_categories VALUES (35, 2, 35, 0);
INSERT INTO Supplier_categories VALUES (258, 2, 258, 0);
INSERT INTO Supplier_categories VALUES (37, 2, 37, 0);
INSERT INTO Supplier_categories VALUES (38, 2, 38, 0);
INSERT INTO Supplier_categories VALUES (39, 2, 39, 0);
INSERT INTO Supplier_categories VALUES (40, 2, 40, 0);
INSERT INTO Supplier_categories VALUES (41, 2, 41, 0);
INSERT INTO Supplier_categories VALUES (273, 2, 273, 0);
INSERT INTO Supplier_categories VALUES (274, 3, 274, 0);
INSERT INTO Supplier_categories VALUES (44, 3, 44, 0);
INSERT INTO Supplier_categories VALUES (45, 3, 45, 0);
INSERT INTO Supplier_categories VALUES (290, 3, 290, 0);
INSERT INTO Supplier_categories VALUES (47, 3, 47, 0);
INSERT INTO Supplier_categories VALUES (292, 3, 292, 0);
INSERT INTO Supplier_categories VALUES (293, 3, 293, 0);
INSERT INTO Supplier_categories VALUES (50, 4, 50, 0);
INSERT INTO Supplier_categories VALUES (51, 4, 51, 0);
INSERT INTO Supplier_categories VALUES (52, 4, 52, 0);
INSERT INTO Supplier_categories VALUES (53, 4, 53, 0);
INSERT INTO Supplier_categories VALUES (54, 4, 54, 0);
INSERT INTO Supplier_categories VALUES (55, 4, 55, 0);
INSERT INTO Supplier_categories VALUES (56, 4, 56, 0);
INSERT INTO Supplier_categories VALUES (57, 4, 57, 0);
INSERT INTO Supplier_categories VALUES (58, 4, 58, 0);
INSERT INTO Supplier_categories VALUES (59, 5, 59, 0);
INSERT INTO Supplier_categories VALUES (60, 5, 60, 0);
INSERT INTO Supplier_categories VALUES (61, 5, 61, 0);
INSERT INTO Supplier_categories VALUES (62, 5, 62, 0);
INSERT INTO Supplier_categories VALUES (63, 5, 63, 0);
INSERT INTO Supplier_categories VALUES (64, 5, 64, 0);
INSERT INTO Supplier_categories VALUES (65, 5, 65, 0);
INSERT INTO Supplier_categories VALUES (66, 5, 66, 0);
INSERT INTO Supplier_categories VALUES (67, 5, 67, 0);
INSERT INTO Supplier_categories VALUES (68, 5, 68, 0);
INSERT INTO Supplier_categories VALUES (69, 6, 69, 0);
INSERT INTO Supplier_categories VALUES (450, 6, 450, 0);
INSERT INTO Supplier_categories VALUES (456, 6, 456, 0);
INSERT INTO Supplier_categories VALUES (72, 6, 72, 0);
INSERT INTO Supplier_categories VALUES (465, 6, 465, 0);
INSERT INTO Supplier_categories VALUES (74, 6, 74, 0);
INSERT INTO Supplier_categories VALUES (75, 6, 75, 0);
INSERT INTO Supplier_categories VALUES (76, 6, 76, 0);
INSERT INTO Supplier_categories VALUES (77, 6, 77, 0);
INSERT INTO Supplier_categories VALUES (477, 6, 477, 0);
INSERT INTO Supplier_categories VALUES (79, 6, 79, 0);
INSERT INTO Supplier_categories VALUES (80, 6, 80, 0);
INSERT INTO Supplier_categories VALUES (481, 6, 481, 0);
INSERT INTO Supplier_categories VALUES (482, 6, 482, 0);
INSERT INTO Supplier_categories VALUES (483, 6, 483, 0);
INSERT INTO Supplier_categories VALUES (489, 6, 489, 0);
INSERT INTO Supplier_categories VALUES (85, 7, 85, 0);
INSERT INTO Supplier_categories VALUES (86, 7, 86, 0);
INSERT INTO Supplier_categories VALUES (87, 7, 87, 0);
INSERT INTO Supplier_categories VALUES (88, 7, 88, 0);
INSERT INTO Supplier_categories VALUES (512, 7, 512, 0);
INSERT INTO Supplier_categories VALUES (90, 8, 90, 0);
INSERT INTO Supplier_categories VALUES (91, 8, 91, 0);
INSERT INTO Supplier_categories VALUES (92, 8, 92, 0);
INSERT INTO Supplier_categories VALUES (521, 8, 521, 0);
INSERT INTO Supplier_categories VALUES (94, 8, 94, 0);
INSERT INTO Supplier_categories VALUES (95, 8, 95, 0);
INSERT INTO Supplier_categories VALUES (530, 8, 530, 0);
INSERT INTO Supplier_categories VALUES (531, 8, 531, 0);
INSERT INTO Supplier_categories VALUES (98, 8, 98, 0);
INSERT INTO Supplier_categories VALUES (99, 8, 99, 0);
INSERT INTO Supplier_categories VALUES (533, 8, 533, 0);
INSERT INTO Supplier_categories VALUES (101, 8, 101, 0);
INSERT INTO Supplier_categories VALUES (102, 102, 102, 0);
INSERT INTO Supplier_categories VALUES (534, 102, 534, 0);
INSERT INTO Supplier_categories VALUES (104, 10, 104, 0);
INSERT INTO Supplier_categories VALUES (105, 10, 105, 0);
INSERT INTO Supplier_categories VALUES (549, 10, 549, 0);
INSERT INTO Supplier_categories VALUES (107, 10, 107, 0);
INSERT INTO Supplier_categories VALUES (108, 10, 108, 0);
INSERT INTO Supplier_categories VALUES (109, 10, 109, 0);
INSERT INTO Supplier_categories VALUES (110, 11, 110, 0);
INSERT INTO Supplier_categories VALUES (111, 11, 111, 0);
INSERT INTO Supplier_categories VALUES (112, 11, 112, 0);
INSERT INTO Supplier_categories VALUES (113, 11, 113, 0);
INSERT INTO Supplier_categories VALUES (114, 12, 114, 0);
INSERT INTO Supplier_categories VALUES (360, 12, 360, 0);
INSERT INTO Supplier_categories VALUES (116, 12, 116, 0);
INSERT INTO Supplier_categories VALUES (117, 12, 117, 0);
INSERT INTO Supplier_categories VALUES (118, 12, 118, 0);
INSERT INTO Supplier_categories VALUES (119, 12, 119, 0);
INSERT INTO Supplier_categories VALUES (120, 12, 120, 0);
INSERT INTO Supplier_categories VALUES (121, 12, 121, 0);
INSERT INTO Supplier_categories VALUES (122, 12, 122, 0);
INSERT INTO Supplier_categories VALUES (123, 12, 123, 0);
INSERT INTO Supplier_categories VALUES (654, 12, 654, 0);
INSERT INTO Supplier_categories VALUES (125, 12, 125, 0);
INSERT INTO Supplier_categories VALUES (126, 13, 126, 0);
INSERT INTO Supplier_categories VALUES (127, 13, 127, 0);
INSERT INTO Supplier_categories VALUES (668, 13, 668, 0);
INSERT INTO Supplier_categories VALUES (129, 13, 129, 0);
INSERT INTO Supplier_categories VALUES (691, 14, 691, 0);
INSERT INTO Supplier_categories VALUES (131, 14, 131, 0);
INSERT INTO Supplier_categories VALUES (132, 14, 132, 0);
INSERT INTO Supplier_categories VALUES (133, 14, 133, 0);
INSERT INTO Supplier_categories VALUES (134, 14, 134, 0);
INSERT INTO Supplier_categories VALUES (689, 14, 689, 0);
INSERT INTO Supplier_categories VALUES (692, 14, 692, 0);
INSERT INTO Supplier_categories VALUES (708, 14, 708, 0);
INSERT INTO Supplier_categories VALUES (138, 15, 138, 0);
INSERT INTO Supplier_categories VALUES (139, 15, 139, 0);
INSERT INTO Supplier_categories VALUES (140, 15, 140, 0);
INSERT INTO Supplier_categories VALUES (141, 15, 141, 0);
INSERT INTO Supplier_categories VALUES (142, 15, 142, 0);
INSERT INTO Supplier_categories VALUES (143, 15, 143, 0);
INSERT INTO Supplier_categories VALUES (144, 15, 144, 0);
INSERT INTO Supplier_categories VALUES (145, 15, 145, 0);
INSERT INTO Supplier_categories VALUES (146, 15, 146, 0);
INSERT INTO Supplier_categories VALUES (147, 15, 147, 0);
INSERT INTO Supplier_categories VALUES (148, 16, 148, 0);
INSERT INTO Supplier_categories VALUES (149, 16, 149, 0);
INSERT INTO Supplier_categories VALUES (150, 16, 150, 0);
INSERT INTO Supplier_categories VALUES (151, 16, 151, 0);
INSERT INTO Supplier_categories VALUES (152, 16, 152, 0);
INSERT INTO Supplier_categories VALUES (153, 16, 153, 0);
INSERT INTO Supplier_categories VALUES (154, 16, 154, 0);
INSERT INTO Supplier_categories VALUES (833, 16, 833, 0);
INSERT INTO Supplier_categories VALUES (156, 16, 156, 0);
INSERT INTO Supplier_categories VALUES (157, 16, 157, 0);
INSERT INTO Supplier_categories VALUES (158, 16, 158, 0);
INSERT INTO Supplier_categories VALUES (159, 16, 159, 0);
INSERT INTO Supplier_categories VALUES (160, 16, 160, 0);
INSERT INTO Supplier_categories VALUES (161, 16, 161, 0);
INSERT INTO Supplier_categories VALUES (864, 16, 864, 0);
INSERT INTO Supplier_categories VALUES (163, 16, 163, 0);
INSERT INTO Supplier_categories VALUES (164, 16, 164, 0);
INSERT INTO Supplier_categories VALUES (165, 16, 165, 0);
INSERT INTO Supplier_categories VALUES (166, 17, 166, 0);
INSERT INTO Supplier_categories VALUES (167, 17, 167, 0);
INSERT INTO Supplier_categories VALUES (168, 17, 168, 0);
INSERT INTO Supplier_categories VALUES (169, 18, 169, 0);
INSERT INTO Supplier_categories VALUES (170, 18, 170, 0);
INSERT INTO Supplier_categories VALUES (171, 18, 171, 0);
